const config = {
  baseURL: 'https://www.lennysnewsletter.com/about',
  set: {
    title: 'div.post-header h1.post-title.unpublished',
    article: '.newsletter-post div.available-content div.body.markup',
  },
  filename: 'lenny.json',
  urls: [
    'https://www.lennysnewsletter.com/p/mission-vision-strategy-goals-roadmap',
    'https://www.lennysnewsletter.com/p/my-favorite-templates-issue-37',
    'https://www.lennysnewsletter.com/p/content-driven-growth-strategy',
    'https://www.lennysnewsletter.com/p/crafting-an-seo-strategy-issue-34',
    'https://www.lennysnewsletter.com/p/winning-at-consumer-subscription',
    'https://www.lennysnewsletter.com/p/product-sense',
    'https://www.lennysnewsletter.com/p/what-is-good-retention-issue-29',
    'https://www.lennysnewsletter.com/p/monthly-churn-benchmarks',
    'https://www.lennysnewsletter.com/p/payback-period',
    'https://www.lennysnewsletter.com/p/what-is-a-good-activation-rate',
    'https://www.lennysnewsletter.com/p/how-to-determine-your-activation',
    'https://www.lennysnewsletter.com/p/measuring-cohort-retention',
    'https://www.lennysnewsletter.com/p/creating-buzz-at-launch',
    'https://www.lennysnewsletter.com/p/what-is-a-good-growth-rate',
    'https://www.lennysnewsletter.com/p/prioritizing',
    'https://www.lennysnewsletter.com/p/kickstarting-and-scaling-a-consumer',
    'https://www.lennysnewsletter.com/p/the-most-important-bottom-up-saas',
    'https://www.lennysnewsletter.com/p/the-most-important-marketplace-metrics',
    'https://www.lennysnewsletter.com/p/the-most-important-consumer-metrics',
    'https://www.lennysnewsletter.com/p/the-most-important-consumer-subscription',
    'https://www.lennysnewsletter.com/p/how-to-know-if-youve-got-productmarket',
    'https://www.lennysnewsletter.com/p/what-it-feels-like-when-youve-found',
    'https://www.lennysnewsletter.com/p/time-to-product-market-fit',
    'https://www.lennysnewsletter.com/p/wedge',
    'https://www.lennysnewsletter.com/p/validating-your-startup-idea',
    'https://www.lennysnewsletter.com/p/what-is-product-management',
    'https://www.lennysnewsletter.com/p/how-to-get-into-product-management',
    'https://www.lennysnewsletter.com/p/how-to-kickstart-and-scale-a-marketplace',
    'https://www.lennysnewsletter.com/p/getting-better-at-product-strategy',
    'https://www.lennysnewsletter.com/p/become-a-product-manager',
    'https://www.lennysnewsletter.com/p/senior-product-manager',
    'https://www.lennysnewsletter.com/p/joining-as-the-first-product-manager',
    'https://www.lennysnewsletter.com/p/jobs-of-product-manager',
    'https://www.lennysnewsletter.com/p/product-management-survey',
    'https://www.lennysnewsletter.com/p/how-figma-builds-product',
    'https://www.lennysnewsletter.com/p/managing-up',
    'https://www.lennysnewsletter.com/p/how-to-know-when-to-stop',
    'https://www.lennysnewsletter.com/p/my-favorite-pm-courses',
    'https://www.lennysnewsletter.com/p/how-the-biggest-consumer-apps-got',
    'https://www.lennysnewsletter.com/p/my-favorite-pm-interview-questions',
    'https://www.lennysnewsletter.com/p/how-to-get-better-at-influence',
    'https://www.lennysnewsletter.com/p/hiring-growth',
    'https://www.lennysnewsletter.com/p/14-habits-of-highly-effective-product',
    'https://www.lennysnewsletter.com/p/doing-a-good-job-product-manager',
    'https://www.lennysnewsletter.com/p/when-to-hire-your-first-product-manager',
    'https://www.lennysnewsletter.com/p/distribution-advantages',
    'https://www.lennysnewsletter.com/p/how-to-interview-product-managers',
    'https://www.lennysnewsletter.com/p/negotiating-comp',
    'https://www.lennysnewsletter.com/p/minto-pyramid-principle-scr',
    'https://www.lennysnewsletter.com/p/startup-to-exit-lessons-from-a-first',
    'https://www.lennysnewsletter.com/p/how-todays-fastest-growing-b2b-businesses',
    'https://www.lennysnewsletter.com/p/how-to-activate-your-investor-network',
    'https://www.lennysnewsletter.com/p/a-playbook-for-fundraising',
    'https://www.lennysnewsletter.com/p/building-community',
    'https://www.lennysnewsletter.com/p/increasing-velocity-issue-61',
    'https://www.lennysnewsletter.com/p/saas-pricing-strategy',
    'https://www.lennysnewsletter.com/p/how-to-increase-your-products-retention',
    'https://www.lennysnewsletter.com/p/freemium-trials-free',
    'https://www.lennysnewsletter.com/p/the-top-5-things-pms-should-know',
    'https://www.lennysnewsletter.com/p/sales-bottom-up',
    'https://www.lennysnewsletter.com/p/the-racecar-growth-frameworkexpanded',
    'https://www.lennysnewsletter.com/p/gtm-motions',
    'https://www.lennysnewsletter.com/p/positioning',
    'https://www.lennysnewsletter.com/p/this-week-21-strategy-and-tactics',
    'https://www.lennysnewsletter.com/p/increasing-virality',
    'https://www.lennysnewsletter.com/p/this-week-16-building-a-referrals',
  ],
};

module.exports = config;
